name: Generate PDF

on:
  push:
    branches:
      - main

jobs:
  generate-pdf:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    # Datum des letzten Commits erhalten
    - name: Get Last Commit Date
      run: |
        echo "LAST_UPDATED_DATE=$(git log -1 --format=%cd --date=short)" >> $GITHUB_ENV

    # Temporäre Markdown-Datei vorbereiten
    - name: Prepare Markdown for PDF
      run: |
        mkdir -p temp
        cp docs/spielordnung.md temp/spielordnung_temp.md
        # Ersetzen des Datums
        sed -i "s/{{ site.time | date: \"%Y-%m-%d\" }}/${{ env.LAST_UPDATED_DATE }}/g" temp/spielordnung_temp.md
        # Ersetzen der Jekyll-TOC-Syntax durch LaTeX-Befehle und Seitenumbruch
        sed -i '/^\* TOC$/{N;s|.*\n.*$|\\clearpage\\renewcommand{\\contentsname}{Inhaltsverzeichnis}\n\\tableofcontents\n\\clearpage|}' temp/spielordnung_temp.md
        # Titel im PDF präsenter machen (LaTeX spezifisch)
        sed -i 's|<div class="title" style="text-align: center;">|\\vspace*{2cm}\\begin{center}\\Huge\\textbf|' temp/spielordnung_temp.md
        sed -i 's|</div>|\\end{center}\\vspace{1cm}|' temp/spielordnung_temp.md
    # Pandoc und LaTeX installieren
    - name: Install Pandoc and LaTeX
      run: |
        sudo apt-get update
        sudo apt-get install -y pandoc texlive texlive-latex-extra texlive-fonts-recommended lmodern
        sudo apt-get install -y texlive-xetex

    # Markdown zu PDF konvertieren
    - name: Convert Markdown to PDF
      run: |
        mkdir -p assets/pdf
        pandoc temp/spielordnung_temp.md -o assets/pdf/spielordnung.pdf \
          --toc-depth=2 \
          --pdf-engine=xelatex \
          -V geometry:margin=1in \
          --resource-path=.:assets/images

    # Aktualisiertes PDF in das Repository committen
    - name: Commit PDF to repository
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
        git add assets/pdf/spielordnung.pdf
        git commit -m "Update PDF version of Spielordnung"
        git push origin main
