name: Generate PDF

on:
  push:
    branches:
      - main

jobs:
  generate-pdf:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    # Get the date of the last commit and set it as an environment variable
    - name: Get Last Commit Date
      run: |
        echo "LAST_UPDATED_DATE=$(git log -1 --format=%cd --date=short)" >> $GITHUB_ENV

    # Create a temporary copy of the Markdown file with placeholders replaced
    - name: Prepare Markdown for PDF
      run: |
        mkdir -p temp
        cp docs/spielordnung.md temp/spielordnung_temp.md
        # Replace the date placeholder
        sed -i "s/{{ site.time | date: \"%Y-%m-%d\" }}/${{ env.LAST_UPDATED_DATE }}/g" temp/spielordnung_temp.md
        # Replace the Jekyll TOC syntax with Pandoc TOC syntax
        sed -i '/^\* TOC$/{N;s/.*\n.*$/[TOC]/}' temp/spielordnung_temp.md

    # Install Pandoc and LaTeX dependencies
    - name: Install Pandoc and LaTeX
      run: |
        sudo apt-get update
        sudo apt-get install -y pandoc texlive texlive-latex-extra texlive-fonts-recommended lmodern
        sudo apt-get install -y texlive-xetex

    # Convert the temporary Markdown file to PDF using Pandoc
    - name: Convert Markdown to PDF
      run: |
        mkdir -p assets/pdf
        pandoc temp/spielordnung_temp.md -o assets/pdf/spielordnung.pdf \
          --toc --toc-depth=2 \
          --pdf-engine=xelatex \
          -V toc-title="Inhaltsverzeichnis" \
          -V geometry:margin=1in \
          --resource-path=.:assets/images

    # Commit the updated PDF back to the repository
    - name: Commit PDF to repository
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
        git add assets/pdf/spielordnung.pdf
        git commit -m "Update PDF version of Spielordnung"
        git push origin main
