name: Generate PDF and Add Commit Date

on:
  push:
    branches:
      - main

jobs:
  update-content:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # Schreibberechtigung für den Repository-Inhalt

    steps:
    # Checkout repository
    - name: Checkout repository
      uses: actions/checkout@v3

  generate-pdf:
    runs-on: ubuntu-latest
    needs: update-content  # Ensure PDF generation waits for content update
    steps:
    # Checkout repository after update
    - name: Checkout repository
      uses: actions/checkout@v3

    # Install Pandoc, LaTeX, and texlive-xetex for PDF generation
    - name: Install Pandoc and LaTeX
      run: |
        sudo apt-get update
        sudo apt-get install -y pandoc texlive texlive-latex-extra texlive-fonts-recommended lmodern
        sudo apt-get install -y texlive-xetex

    # Convert the Markdown file to PDF and save in assets/pdf/
    - name: Convert Markdown to PDF
      run: |
        mkdir -p assets/pdf
        pandoc docs/spielordnung.md -o assets/pdf/spielordnung.pdf --toc --toc-depth=2 --pdf-engine=xelatex -V geometry:margin=1in --resource-path=.:assets/images

    # Commit the PDF back to the repository
    - name: Commit PDF to repository
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
        git add assets/pdf/spielordnung.pdf
        git commit -m "Update PDF version of Spielordnung"
        git push origin main
