name: Generate PDF and Add Commit Date

on:
  push:
    branches:
      - main

jobs:
  generate-pdf:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # Schreibberechtigung für den Repository-Inhalt

    steps:
    # Checkout repository
    - name: Checkout repository
      uses: actions/checkout@v3

    # Get the date of the last commit and set it as an environment variable
    - name: Get Last Commit Date
      run: |
        echo "date=$(git log -1 --format=%cd --date=short)" >> $GITHUB_ENV

    # Install Pandoc, LaTeX, and xelatex for PDF generation
    - name: Install Pandoc and LaTeX
      run: |
        sudo apt-get update
        sudo apt-get install -y pandoc texlive texlive-latex-extra texlive-fonts-recommended lmodern
        sudo apt-get install -y xelatex

    # Replace the placeholder LAST_UPDATED_DATE in the docs/spielordnung.md file with the last commit date
    - name: Replace LAST_UPDATED_DATE in Markdown
      run: |
        sed -i "s/LAST_UPDATED_DATE/${{ env.date }}/" docs/spielordnung.md

    # Convert the Markdown file to PDF and save in assets/pdf/
    - name: Convert Markdown to PDF
      run: |
        mkdir -p assets/pdf
        pandoc docs/spielordnung.md -o assets/pdf/spielordnung.pdf --toc --toc-depth=2 --pdf-engine=xelatex -V geometry:margin=1in --resource-path=assets/images
     
    # Commit the PDF back to the repository
    - name: Commit PDF to repository
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
        git add assets/pdf/spielordnung.pdf
        git commit -m "Update PDF version of Spielordnung"
        git push origin main
