name: Generate Minimal PDF

on:
  push:
    branches:
      - main

jobs:
  generate-pdf:
    runs-on: ubuntu-latest

    steps:
    # Checkout repository
    - name: Checkout repository
      uses: actions/checkout@v3

    # Install Pandoc and LaTeX for PDF generation
    - name: Install Pandoc and LaTeX
      run: |
        sudo apt-get update
        sudo apt-get install -y pandoc texlive texlive-latex-extra texlive-fonts-recommended lmodern
        sudo apt-get install -y texlive-xetex

    # Convert the minimal Markdown file to PDF and save in assets/pdf/
    - name: Convert Markdown to PDF
      run: |
        mkdir -p assets/pdf
        pandoc docs/minimal.md -o assets/pdf/minimalbeispiel.pdf \
          --pdf-engine=xelatex \
          -V geometry:margin=1in \
          --resource-path=.:assets/images

    # Commit the updated PDF back to the repository
    - name: Commit PDF to repository
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
        git add assets/pdf/minimalbeispiel.pdf
        git commit -m "Update PDF version of Minimalbeispiel"
        git push origin main
