name: Generate PDF from Jekyll Site

on:
  push:
    branches:
      - main

jobs:
  build-and-generate-pdf:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Setup Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.0'  # Passen Sie die Ruby-Version bei Bedarf an

    - name: Install Jekyll and Dependencies
      run: |
        gem install jekyll webrick

    - name: Build Jekyll Site
      run: jekyll build

    - name: Install wkhtmltopdf
      run: |
        sudo apt-get update
        sudo apt-get install -y wkhtmltopdf

    - name: Generate PDF from HTML
      run: |
        mkdir -p assets/pdf
        wkhtmltopdf _site/docs/spielordnung.html assets/pdf/spielordnung.pdf

    - name: Commit PDF to repository
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
        git add assets/pdf/spielordnung.pdf
        git commit -m "Update PDF version of Spielordnung"
        git push origin main
