name: Build PDF

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install Pandoc
      run: sudo apt-get install -y pandoc
    - name: Build Jekyll Site
      run: bundle exec jekyll build
    - name: Convert HTML to PDF
      run: pandoc _site/index.html -o output.pdf
    - name: Upload PDF
      uses: actions/upload-artifact@v3
      with:
        name: output-pdf
        path: output.pdf
